name: 'Github Actions Deploy'
description: 'GitHub Action to deploy to GitHub Pages'
author: 'idev-coder'
branding:
  icon: 'upload-cloud'
  color: 'yellow'

inputs:
  github_token: 
    description: 'Github Token'
    required: false
  dist:
    description: 'Base directory for all source files'
    required: false
  branch:
    description: 'Name of the branch you are pushing to'
    required: false
  message:
    description: 'commit message'
    required: false
  repo:
    description: 'URL of the repository you are pushing to'
    required: false
  remote:
    description: 'The name of the remote'
    required: false
  user:
    description: 'The name and email of the user (defaults to the git config).  Format is "Your Name <email@example.com>".'
    required: false
runs:
  using: 'node16'
  main: 'src/index.js'