name: 'Github Actions Deploy'
description: 'GitHub Action to deploy to GitHub Pages'
author: 'idev-coder'
branding:
  icon: 'upload-cloud'
  color: 'yellow'

inputs:
  github_token:
    description: 'Github Token'
    required: false
  dist:
    description: 'Base directory for all source files'
    required: false
  src:
    description: 'Pattern used to select which files to publish'
    required: false
  branch:
    description: 'Name of the branch you are pushing to'
    required: false
  dest:
    description: 'Target directory within the destination branch (relative to the root)'
    required: false
  add:
    description: 'Only add, and never remove existing files'
    required: false
  silent:
    description: 'Do not output the repository url'
    required: false
  message:
    description: 'commit message'
    required: false
  tag:
    description: 'add tag to commit'
    required: false
  git:
    description: 'Path to git executable'
    required: false
  dotfiles:
    description: 'Include dotfiles'
    required: false
  repo:
    description: 'URL of the repository you are pushing to'
    required: false
  depth:
    description: 'depth for clone'
    required: false
  remote:
    description: 'The name of the remote'
    required: false
  user:
    description: 'The name and email of the user (defaults to the git config).  Format is "Your Name <email@example.com>".'
    required: false
  remove:
    description: 'Remove files that match the given pattern (ignored if used together with --add).'
    required: false
  no-push:
    description: 'Commit only (with no push)'
    required: false
  no-history:
    description: 'Push force new commit without parent history'
    required: false
  before-add:
    description: 'Execute the function exported by <file> before "git add"'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'